name: Django CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 44495131
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    env:
      DB_NAME: test_db
      DB_USER: postgres
      DB_PASSWORD: 44495131
      DB_HOST: 127.0.0.1 
      DB_PORT: 5432
      DEBUG: "True"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependecies
        run: pipenv install --dev

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Esperando a que PostgreSQL esté listo..."
          for i in {1..30}; do
            if pg_isready -h 127.0.0.1 -p 5432 -U postgres; then
              echo "PostgreSQL está listo"
              break
            fi
            echo "Esperando a PostgreSQL..."
            sleep 2
          done

      - name: Run migrations
        run: pipenv run python manage.py migrate

      - name: Run tests
        run: pipenv run python manage.py test