name: Django CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 44495131
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg-isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependecies
        run: pipenv install --dev

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h postgres -p 5432; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Run migrations
        run: pipenv run python manage.py migrate

      - name: Run tests
        run: pipenv run python manage.py test